#pragma config(Motor,  port1,           rightMogo,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          leftMogo,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int a;

void driver() {
	if (vexRT[Btn7U]) {
			a = -1;
	}

	else if (vexRT[Btn7D]) {
			a = 1;
	}
	motor[rightDrive] = abs(vexRT[Ch2]) >= 10? a * vexRT[Ch2] : 0;
	motor[leftDrive] = abs(vexRT[Ch3]) >= 10? a * vexRT[Ch3] : 0;

	if (vexRT[Btn5D]) {
		motor[rightMogo] = 90;
		motor[leftMogo] = 90;
		}

	else if (vexRT[Btn6D]) {
		motor[rightMogo] = -90;
		motor[leftMogo] = -90;
	}

	else {
		motor[rightMogo] = 0;
		motor[leftMogo] = 0;
	}


}
task main()
{
	driver();


}
